spring.application.name=spring-batch-billing-job

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres_billing_job_db
spring.datasource.username=postgres
spring.datasource.password=postgres

#spring.batch.job.enabled=false